[package]
name = "4x8matrix/service"
version = "1.0.0"
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
licence = "Unlicense"
authors = ["AsynchronousMatrix"]

description = "An 'Service' that represents a top-level client-sided singleton, designed to be used alongside the Infinity Framework."

exclude = ["**"]
include = ["Source", "Source/*", "default.project.json", "wally.lock", "wally.toml", "LICENCE", "README.md"]

[dev-dependencies]
TestEz = "roblox/testez@0.4.1"
EmoticonReporter = "4x8matrix/emoticon-reporter@1.0.0"

[dependencies]
Console = "4x8matrix/console@2.0.2"